<script lang="ts">
	import type { PageData } from './$types';

	const title = 'The Synthetic Gazette';
	export let data: PageData;

	const today = new Date().toLocaleDateString('en-US', {
		weekday: 'long',
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	});
</script>

<svelte:head>
	<title>{title} | {today}</title>
</svelte:head>

<div class="layout">
	<div class="container">
		<nav class="nav">
			<time class="nav__time">{today}</time>
			{#if data.user}
				<a class="nav__a nav__a--play" href="/play">Play</a>
				<form action="/logout" method="POST" class="nav__form">
					<nav class="nav__auth">
						{data.user.nickname ? data.user.nickname : 'Anonymous'}
						<button class="nav__button" type="submit">Logout</button>
					</nav>
				</form>
			{:else}
				<div class="nav__placeholder" />
				<nav class="nav__auth">
					<a class="nav__a" href="/login">Login</a>
					<a class="nav__a" href="/waitlist">Join waitlist</a>
				</nav>
			{/if}
		</nav>
	</div>

	<div class="container">
		<header class="header">
			<a href="/" class="header__a">
				<h1 class="header__logo">{title}</h1>
				<p class="header__slogan">Generated by AI, curated by humans</p>
			</a>
		</header>
	</div>

	<div class="container">
		<main class="main">
			<slot />
		</main>
	</div>

	<footer class="footer">
		<div class="container">
			<nav class="footer-nav">
				<nav class="footer-nav__links">
					<a href="/" class="footer-nav__logo">{title}</a>
				</nav>

				<nav class="footer-nav__links">
					<a
						href="https://github.com/fmaclen/the-synthetic-gazette"
						class="footer-nav__a"
						target="_blank"
						rel="noreferrer"
					>
						GitHub
					</a>
					<hr class="footer-nav__hr" />
					<a href="/login" class="footer-nav__a">Login</a>
					<a href="/waitlist" class="footer-nav__a">Join waitlist</a>
				</nav>
			</nav>
		</div>
	</footer>
</div>

<style lang="scss">
	@import url('https://fonts.googleapis.com/css2?family=Inter:wght@200;400;600;800&family=Overpass+Mono:wght@300;400;700&display=swap');

	:global(body) {
		--font-base: 'Inter', sans-serif;
		--font-mono: 'Overpass Mono', monospace;

		--color-accent: slateblue;
		--color-positive: #00b376;

		--color-border: #e2e2e2;

		--color-white: #ffffff;
		--color-black: #000;

		--color-grey3: #fafafa;
		--color-grey5: #f2f2f2;
		--color-grey7: #ededed;
		--color-grey10: #e6e6e6;
		--color-grey20: #cccccc;
		--color-grey30: #b2b2b2;
		--color-grey40: #999999;
		--color-grey50: #7f7f7f;
		--color-grey60: #666;
		--color-grey70: #4c4c4c;
		--color-grey80: #333333;
		--color-grey90: #191919;

		margin: 0;
		font-family: var(--font-base);
		color: var(--color-grey90);
	}

	div.layout {
		display: grid;
		grid-template-rows: max-content max-content auto max-content;
		min-height: 100vh;
		row-gap: 48px;
	}

	div.container {
		display: grid;
		align-items: center;
		width: 100%;
		max-width: 1440px;
		margin-inline: auto;
		box-sizing: border-box;

		--container-padding: 4rem;
		padding-left: var(--container-padding);
		padding-right: var(--container-padding);

		@media (max-width: 1440px) {
			--container-padding: 2rem;
		}

		@media (max-width: 720px) {
			--container-padding: 1rem;
		}
	}

	nav.nav {
		display: grid;
		width: 100%;
		grid-template-columns: repeat(3, 1fr);
		align-items: center;
		justify-content: space-between;
		border-bottom: 1px solid #e2e2e2;
		padding: 1rem 0;
		font-size: 14px;
		column-gap: 32px;
		text-align: center;

		> *:first-child {
			text-align: left;
			margin-right: auto;
		}
		> *:last-child {
			text-align: right;
			margin-left: auto;
		}
	}

	form.nav__form {
		display: flex;
		align-items: center;
		gap: 1rem;
	}

	button.nav__button,
	a.nav__a {
		font-family: var(--font-base);
		line-height: 1em;
		font-weight: 600;
		text-decoration: none;
		color: inherit;

		&:hover {
			color: var(--color-accent);
		}
	}

	a.nav__a--play {
		display: inline-flex;
		font-size: 16px;
		max-width: max-content;
		color: var(--color-white);
		background-color: var(--color-grey90);
		margin-inline: auto;
		padding: 28px 24px;
		margin-bottom: -32px;
		transition: all 100ms;

		&:hover {
			color: var(--color-white);
			background-color: var(--color-accent);
		}

		&:active {
			transform: scale(0.95);
			background-color: var(--color-positive);
		}
	}

	button.nav__button {
		font-size: 14px;
		border: none;
		padding: 0;
		background: transparent;
		cursor: pointer;
	}

	nav.nav__auth {
		display: flex;
		column-gap: 16px;
	}

	header.header {
		display: flex;
		flex-direction: column;
		row-gap: 3rem;
		width: 100%;
	}

	a.header__a {
		display: inline-block;
		text-decoration: none;
		color: inherit;
		padding: 0.5rem 1rem;
		margin-inline: auto;
	}

	h1.header__logo {
		font-family: var(--font-base);
		text-align: center;
		letter-spacing: -0.065em;
		margin-top: 32px;
		margin-bottom: 8px;
		font-size: 48px;
		line-height: 1em;
	}

	p.header__slogan {
		font-size: 14px;
		font-family: var(--font-mono);
		text-align: center;
		color: #999;
		margin: 0;
	}

	footer.footer {
		background-color: #222;
		padding: 32px;
	}

	nav.footer-nav {
		display: flex;
		width: 100%;
		column-gap: 32px;
		justify-content: space-between;
	}

	nav.footer-nav__links {
		display: flex;
		column-gap: 16px;
	}

	a.footer-nav__a,
	a.footer-nav__logo {
		font-family: var(--font-base);
		font-size: 16px;
		font-weight: 600;
		color: #fff;
		text-decoration: none;

		&:hover {
			opacity: 0.75;
		}
	}

	a.footer-nav__logo {
		letter-spacing: -0.035em;
	}

	a.footer-nav__a {
		font-size: 14px;
		font-weight: 400;
	}

	hr.footer-nav__hr {
		height: 100%;
		border: 0;
		margin: 0;
		padding: 0;
		width: 1px;
		background-color: var(--color-grey70);
	}
</style>
