<script lang="ts">
	import ArticleSummaries from '$lib/components/ArticleSummaries.svelte';
	import HR from '$lib/components/HR.svelte';
	import Head from '$lib/components/Head.svelte';
	import Notice from '$lib/components/Notice.svelte';
	import Section from '$lib/components/Section.svelte';

	import type { PageData } from './$types';

	export let data: PageData;

	const today = new Date().toLocaleDateString('en-US', {
		weekday: 'long',
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	});
</script>

<Head title={['Frontpage', today]} />

<Notice>Generated by AI, curated by humans</Notice>
<HR />

<Section>
	<ArticleSummaries articles={data.articles} />
</Section>
