<script lang="ts">
	import ArticleMetadata from '$lib/components/ArticleMetadata.svelte';
	import Button from '$lib/components/Button.svelte';
	import Card from '$lib/components/Card.svelte';
	import HR from '$lib/components/HR.svelte';
	import Notice from '$lib/components/Notice.svelte';
	import Section from '$lib/components/Section.svelte';

	import type { PageData } from './$types';

	export let data: PageData;
</script>

<Notice>Generated by AI, curated by humans</Notice>
<HR />

<Section>
	<div class="articles">
		{#each data.articles as article}
			<Card>
				<a class="article" href="/article/{article.id}">
					<div class="article__body">
						<h3 class="article__category">{article.category}</h3>
						<h1 class="article__headline">
							{article.headline}
						</h1>
						<p class="article__p">{article.body[0]}</p>
					</div>
				</a>

				<ArticleMetadata
					id={article.author.id}
					nickname={article.author.nickname}
					updated={article.updated}
				>
					<a class="article-reactions-summary" href="/article/{article.id}">
						<span class="article-reactions-summary__emoji">
							{article.reactions.total > 0
								? article.reactions.byType.sort((a, b) => b.total - a.total)[0].reaction
								: ''}
						</span>
						<span class="article-reactions-summary__total">{article.reactions.total}</span>
					</a>
				</ArticleMetadata>
			</Card>
		{/each}
	</div>
</Section>

<style lang="scss">
	div.articles {
		display: flex;
		align-items: center;
		flex-direction: column;
		row-gap: 16px;
	}

	a.article {
		text-decoration: none;
	}

	div.article__body {
		border-top-left-radius: 2px;
		border-top-right-radius: 2px;
		background-color: var(--color-white);
		padding: 20px;
		display: flex;
		flex-direction: column;
		row-gap: 8px;
	}

	h3.article__category {
		margin: 0;
		font-size: 13px;
		line-height: 1em;
		font-weight: 400;
		color: var(--color-accent);
	}

	h1.article__headline {
		font-family: var(--font-serif);
		margin: 0;
		font-size: 24px;
		line-height: 1.1em;
		color: hsl(0, 0%, 10%);
	}

	p.article__p {
		font-size: 14px;
		margin: 0;
		color: hsl(0, 0%, 40%);
		line-height: 1.4em;
	}

	a.article-reactions-summary {
		display: flex;
		align-items: center;
		column-gap: 8px;
		text-decoration: none;

		font-family: var(--font-mono);
		font-size: 12px;
		line-height: 1em;
		text-align: center;
		font-weight: 400;
		color: hsl(0, 0%, 50%);
	}

	span.article-reactions-summary__emoji {
		font-size: 16px;
	}
</style>
