import { expect, test } from '@playwright/test';

test('index page has expected h1', async ({ page }) => {
	await page.goto('/');
	expect(await page.textContent('div.notice')).toBe('Generated by AI, curated by humans');
});
