import type { Article, ArticleStatus } from '$lib/article';
import type { MockArticle } from '$lib/tests';
import { type Page, expect } from '@playwright/test';
import PocketBase, { BaseAuthStore } from 'pocketbase';

import { TEST_ADMIN_PASSWORD, TEST_ADMIN_USER } from './fixtures.js';

interface User {
	email: string;
	nickname: string;
	password: string;
	passwordConfirm: string;
	terms: boolean;
}

let pb: PocketBase;

export async function resetDatabase(): Promise<void> {
	pb = new PocketBase(process.env.TEST_POCKETBASE_URL);
	await pb.admins.authWithPassword(TEST_ADMIN_USER, TEST_ADMIN_PASSWORD);

	// Delete all reactions
	const reactions = await pb.collection('reactions').getFullList(200);
	for (const reaction of reactions) {
		await pb.collection('reactions').delete(reaction.id);
	}

	// Delete all articles
	const articles = await pb.collection('articles').getFullList(200);
	for (const article of articles) {
		await pb.collection('articles').delete(article.id);
	}

	// Delete all users
	const users = await pb.collection('users').getFullList(200);
	for (const user of users) {
		await pb.collection('users').delete(user.id);
	}
}

export async function createUser(user: User): Promise<void> {
	await pb.collection('users').create(user);
}

export async function getUser(email: string): Promise<BaseAuthStore['model']> {
	return await pb.collection('users').getFirstListItem(`email = "${email}"`);
}

export async function verifyUser(email: string): Promise<void> {
	const user = await getUser(email);
	user && (await pb.collection('users').update(user.id, { verified: true }));
}

export async function loginUser(user: User, page: Page): Promise<void> {
	await page.goto('/login');
	await page.getByLabel('E-mail').fill(user.email);
	await page.getByLabel('Password', { exact: true }).fill(user.password);
	await page.locator('button[type=submit]', { hasText: 'Login' }).click();
	await expectToBeInHomepage(page);
}

export async function createAndLoginUser(user: User, page: Page): Promise<void> {
	await createUser(user);
	await verifyUser(user.email);
	await loginUser(user, page);
}

export async function logoutCurrentUser(page: Page) {
	await page.click('button[aria-label="Toggle navigation"]');
	await page.getByText('Logout').click();
}

export async function getLastArticle(query: string): Promise<any> {
	return await pb.collection('articles').getFirstListItem(query, { sort: '-created' });
}

export async function createArticle(
	mockArticle: MockArticle,
	status: ArticleStatus,
	user: string
): Promise<BaseAuthStore['model']> {
	return await pb.collection('articles').create({
		...mockArticle,
		body: JSON.stringify(mockArticle.body),
		messages: JSON.stringify(mockArticle.messages),
		status,
		user
	});
}

export async function updateArticle(id: string, formData: FormData) {
	await pb.collection('articles').update(id, formData);
}

export async function expectToBeInHomepage(page: Page) {
	await expect(page.getByText('Generated by AI, curated by humans')).toBeVisible();
}

export async function goToHomepageViaLogo(page: Page) {
	await page.locator('a.logo').click();
	await expectToBeInHomepage(page);
}

export const prepareToAcceptDialog = async (page: Page, message: RegExp) => {
	page.on('dialog', (dialog) => {
		expect(dialog.message()).toMatch(message);

		dialog.accept();
	});
};
