#!/bin/bash

# This script is used to deploy the app to the server: it pulls the latest
# changes from Github, installs dependencies, builds the frontend, and restarts the
# backend (applying migrations) and frontend.

# Pull the latest changes from git
git pull

# Check if deploy script is in "quick" mode
if [ "$1" != "-q" ]; then
    # Run npm i if needed
    if [ -e "package-lock.json" ]; then
        npm ci
    else
        npm i
    fi
fi

# Run npm run build
npm run build

# Restart backend
pkill -f "./pocketbase serve APP_NAME=promptspree-backend"
nohup bash -c "cd pocketbase/ && ./pocketbase serve APP_NAME=promptspree-backend" &

# Load environment variables and restart frontend
pkill -f "node build/index.js APP_NAME=promptspree-frontend"
env $(cat .env | xargs) nohup node build/index.js APP_NAME=promptspree-frontend &
