#!/bin/bash

# This script runs "npm run dev" while including the environment variables found in the .env file.

set -a # automatically exports all variables
source .env
npx vite dev --host # Dev server accessible from other devices on the network
set +a # stops automatically exporting all variables
