#!/bin/bash

# This script downloads and installs Pocketbase for the current OS

# Check the current OS
case $(uname | tr '[:upper:]' '[:lower:]') in
  darwin*)
    OS="darwin"
    if [[ $(uname -m) == "arm64" ]]; then
      OS="$OS"_arm64
    else
      OS="$OS"_amd64
    fi
    ;;
  linux*)
    OS="linux"
    if [[ $(uname -m) == "armv7l" ]]; then
      OS="$OS"_armv7
    elif [[ $(uname -m) == "aarch64" ]]; then
      OS="$OS"_arm64
    else
      OS="$OS"_amd64
    fi
    ;;
  msys*)
    OS="windows"
    if [[ $(uname -m) == "arm64" ]]; then
      OS="$OS"_arm64
    else
      OS="$OS"_amd64
    fi
    ;;
  *)
    echo "-> Unsupported OS: $(uname)"
    exit 1
    ;;
esac

# Download the latest version of Pocketbase for the current OS
URL="https://github.com/pocketbase/pocketbase/releases/download/v0.12.3/pocketbase_0.12.3_$OS.zip"
echo "-> Downloading $URL ..."
curl -L -o pocketbase.zip $URL

# Unzip the file to ./pocketbase
echo "-> Unzipping pocketbase.zip ..."
unzip -o pocketbase.zip -d ./pocketbase

# Clean up the zip file
echo "-> Cleaning up ..."
rm pocketbase.zip

echo "-> Pocketbase has been downloaded and unzipped to ./pocketbase."
