#!/bin/bash

# Set environment variable for Pocketbase URL from .env file
export TEST_POCKETBASE_URL="http://127.0.0.1:8091"

# Delete everything in tests/pocketbase
rm -rf tests/pocketbase/*

# Create the tests/pocketbase directory if it doesn't exist
mkdir -p tests/pocketbase

# Copy migrations from pocketbase/pb_migrations to tests/pocketbase/pb_migrations
cp -rp pocketbase/pb_migrations tests/pocketbase/pb_migrations

# Start pocketbase
# (We use the # operator to remove "http://" from the beginning of TEST_POCKETBASE_URL)
./pocketbase/pocketbase serve --http="${TEST_POCKETBASE_URL#http://}" --dir tests/pocketbase/pb_data --migrationsDir tests/pocketbase/pb_migrations &

# Run npx playwright test
TEST_POCKETBASE_URL=${TEST_POCKETBASE_URL} npx playwright test

# Check the exit status of the test command and exit with the same status code if it's non-zero
status=$? && test $status -eq 0 || exit $status

# Stop pocketbase (assuming it's running in the background)
pkill pocketbase
