<script lang="ts">
	import { page } from '$app/stores';

	export let title: string | string[];
	export let description: string = 'Generated by AI, curated by humans';

	const SEPARATOR = '·';
	const sectionTitle = typeof title !== 'string' ? title.join(` ${SEPARATOR} `) : title;
	$: formattedTitle = `${sectionTitle} ${SEPARATOR} Promptspree`;
</script>

<svelte:head>
	<!-- HTML Meta Tags -->
	<title>{title}</title>
	<meta name="description" content={description} />

	<!-- Facebook Meta Tags -->
	<meta property="og:url" content={$page.url.href} />
	<meta property="og:type" content="website" />
	<meta property="og:title" content={formattedTitle} />
	<meta property="og:description" content={description} />
	<!-- <meta property="og:image" content="" /> -->

	<!-- Twitter Meta Tags -->
	<meta name="twitter:card" content="summary_large_image" />
	<meta property="twitter:domain" content={$page.url.hostname} />
	<meta property="twitter:url" content={$page.url.href} />
	<meta name="twitter:title" content={formattedTitle} />
	<meta name="twitter:description" content={description} />
	<!-- <meta name="twitter:image" content="" /> -->

	<!-- Meta Tags Generated via https://opengraph.dev -->
</svelte:head>
